CREATE TABLE "Usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rol" integer NOT NULL,
  "estado" bit NOT NULL DEFAULT 1,
  "primer_nombre" varchar(50) NOT NULL,
  "segundo_nombre" varchar(100),
  "primer_apellido" varchar(50) NOT NULL,
  "segundo_apellido" varchar(50) NOT NULL,
  "correo" varchar(255) UNIQUE NOT NULL,
  "telefono" varchar(15) UNIQUE NOT NULL,
  "contrasenia" varchar(255) NOT NULL,
  "fecha_creacion" timestamp NOT NULL
);

CREATE TABLE "Rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(25) NOT NULL
);

CREATE TABLE "Medico" (
  "id" integer PRIMARY KEY NOT NULL,
  "id_especialidad" integer NOT NULL,
  "colegiado" varchar(15) NOT NULL
);

CREATE TABLE "Especialidad" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "especialidad" varchar(100) NOT NULL
);

CREATE TABLE "JornadaMedica" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_medico" integer NOT NULL,
  "id_dia_semana" integer NOT NULL,
  "hora_inicio" time NOT NULL,
  "hora_fin" time NOT NULL,
  "duracion_consulta" integer NOT NULL
);

CREATE TABLE "DiaSemana" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dia_semana" varchar(10) NOT NULL
);

CREATE TABLE "Cita" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_medico" integer NOT NULL,
  "id_paciente" integer NOT NULL,
  "id_estado_cita" integer NOT NULL,
  "fecha" date NOT NULL,
  "hora" time NOT NULL
);

CREATE TABLE "EstadoCita" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "estado_cita" varchar(50) NOT NULL
);

CREATE TABLE "Consulta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cita" integer UNIQUE NOT NULL,
  "motivo_consulta" text,
  "diagnostico" text,
  "tratamiento" text,
  "observaciones" text
);

CREATE TABLE "SignosVitales" (
  "id_consulta" integer PRIMARY KEY NOT NULL,
  "peso" decimal(5,2) NOT NULL,
  "altura" decimal(5,2) NOT NULL,
  "presion_sistolica" integer NOT NULL,
  "presion_diastolica" integer NOT NULL,
  "temperatura" decimal(3,1) NOT NULL
);

CREATE TABLE "Documento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" integer NOT NULL,
  "id_categoria_documento" integer NOT NULL,
  "nombre" varchar(255) NOT NULL,
  "url" varchar(500) NOT NULL,
  "fecha_carga" timestamp NOT NULL,
  "id_usuario_carga" integer NOT NULL
);

CREATE TABLE "CategoriaDocumento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoria_documento" varchar(100) NOT NULL
);

CREATE TABLE "AuditoriaDocumento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_documento" integer NOT NULL,
  "nombre_anterior" varchar(255) NOT NULL,
  "url_anterior" varchar(500),
  "id_usuario" integer NOT NULL,
  "fecha_modificacion" timestamp NOT NULL,
  "id_motivo_modificacion" integer NOT NULL,
  "nombre_nuevo" varchar(255) NOT NULL,
  "url_nuevo" varchar(500)
);

CREATE TABLE "MotivoModificacionDocumento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "motivo_modificacion" varchar(50) NOT NULL,
  "detalle_motivo" text
);

CREATE TABLE "AuditoriaConsulta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consulta" integer NOT NULL,
  "motivo_consulta_anterior" text,
  "diagnostico_anterior" text,
  "tratamiento_anterior" text,
  "observaciones_anterior" text,
  "id_usuario" integer NOT NULL,
  "fecha_modificacion" timestamp NOT NULL,
  "id_motivo_modificacion" integer NOT NULL,
  "motivo_consulta_nuevo" text,
  "diagnostico_nuevo" text,
  "tratamiento_nuevo" text,
  "observaciones_nuevo" text
);

CREATE TABLE "MotivoModificacionConsulta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "motivo_modificacion" varchar(50) NOT NULL,
  "detalle_motivo" text
);

CREATE INDEX ON "Usuario" ("primer_nombre", "primer_apellido");

CREATE INDEX ON "Medico" ("colegiado");

CREATE INDEX ON "JornadaMedica" ("id_medico");

CREATE INDEX ON "JornadaMedica" ("id_dia_semana");

CREATE INDEX ON "Paciente" ("primer_nombre", "primer_apellido");

CREATE INDEX ON "Paciente" ("fecha_nacimiento");

CREATE INDEX ON "Cita" ("id_medico", "fecha");

CREATE INDEX ON "Cita" ("id_paciente", "fecha");

CREATE INDEX ON "EstadoCita" ("estado_cita");

CREATE INDEX ON "Documento" ("id_paciente");

CREATE INDEX ON "Documento" ("id_categoria_documento");

CREATE INDEX ON "AuditoriaDocumento" ("id_documento");

CREATE INDEX ON "AuditoriaDocumento" ("id_usuario");

CREATE INDEX ON "AuditoriaDocumento" ("fecha_modificacion");

CREATE INDEX ON "AuditoriaConsulta" ("id_consulta");

CREATE INDEX ON "AuditoriaConsulta" ("id_usuario");

CREATE INDEX ON "AuditoriaConsulta" ("fecha_modificacion");

COMMENT ON TABLE "JornadaMedica" IS 'La duracion de la consulta, es en minutos';

COMMENT ON TABLE "Paciente" IS 'El paciente no tiene unique en el telefono';

COMMENT ON TABLE "SignosVitales" IS 'Penso en KG y Altura en CM';

ALTER TABLE "Usuario" ADD CONSTRAINT "FK_Usuario_Rol" FOREIGN KEY ("id_rol") REFERENCES "Rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Medico" ADD CONSTRAINT "FK_Medico_Usuario" FOREIGN KEY ("id") REFERENCES "Usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Medico" ADD CONSTRAINT "FK_Medico_Especialidad" FOREIGN KEY ("id_especialidad") REFERENCES "Especialidad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "JornadaMedica" ADD CONSTRAINT "FK_JornadaMedica_Medico" FOREIGN KEY ("id_medico") REFERENCES "Medico" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "JornadaMedica" ADD CONSTRAINT "FK_JornadaMedico_DiaSemana" FOREIGN KEY ("id_dia_semana") REFERENCES "DiaSemana" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Cita" ADD CONSTRAINT "FK_Cita_Paciente" FOREIGN KEY ("id_paciente") REFERENCES "Paciente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Cita" ADD CONSTRAINT "FK_Cita_Medico" FOREIGN KEY ("id_medico") REFERENCES "Medico" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Cita" ADD CONSTRAINT "FK_Cita_EstadoCita" FOREIGN KEY ("id_estado_cita") REFERENCES "EstadoCita" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Consulta" ADD CONSTRAINT "FK_Consulta_Cita" FOREIGN KEY ("id_cita") REFERENCES "Cita" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SignosVitales" ADD CONSTRAINT "FK_SignosVitales_Consulta" FOREIGN KEY ("id_consulta") REFERENCES "Consulta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Documento" ADD CONSTRAINT "FK_Documento_Paciente" FOREIGN KEY ("id_paciente") REFERENCES "Paciente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Documento" ADD CONSTRAINT "FK_Documento_CategoriaDocumento" FOREIGN KEY ("id_categoria_documento") REFERENCES "CategoriaDocumento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Documento" ADD CONSTRAINT "FK_Documento_Usuario" FOREIGN KEY ("id_usuario_carga") REFERENCES "Usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuditoriaDocumento" ADD CONSTRAINT "FK_AuditoriaDocumento_Documento" FOREIGN KEY ("id_documento") REFERENCES "Documento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuditoriaDocumento" ADD CONSTRAINT "FK_AuditoriaDocumento_Usuario" FOREIGN KEY ("id_usuario") REFERENCES "Usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuditoriaDocumento" ADD CONSTRAINT "FK_AuditoriaDocumento_MotivoModificacionDocumento" FOREIGN KEY ("id_motivo_modificacion") REFERENCES "MotivoModificacionDocumento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuditoriaConsulta" ADD CONSTRAINT "FK_AuditoriaConsulta_Consulta" FOREIGN KEY ("id_consulta") REFERENCES "Consulta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuditoriaConsulta" ADD CONSTRAINT "FK_AuditoriaConsulta_Usuario" FOREIGN KEY ("id_usuario") REFERENCES "Usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AuditoriaConsulta" ADD CONSTRAINT "FK_AuditoriaConsulta_MotivoModificacionConsulta" FOREIGN KEY ("id_motivo_modificacion") REFERENCES "MotivoModificacionConsulta" ("id") DEFERRABLE INITIALLY IMMEDIATE;
